module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/features/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'dark-text': "#9ca3af",
        admin: {
          primary: 'var(--admin-primary)',
          'primary-hover': 'var(--admin-primary-hover)',
          'primary-light': 'var(--admin-primary-light)',
          'primary-ring': 'var(--admin-primary-ring)',
          success: 'var(--admin-success)',
          'success-light': 'var(--admin-success-light)',
          'success-text': 'var(--admin-success-text)',
          warning: 'var(--admin-warning)',
          'warning-light': 'var(--admin-warning-light)',
          'warning-text': 'var(--admin-warning-text)',
          danger: 'var(--admin-danger)',
          'danger-hover': 'var(--admin-danger-hover)',
          'danger-light': 'var(--admin-danger-light)',
          'danger-text': 'var(--admin-danger-text)',
          info: 'var(--admin-info)',
          'info-light': 'var(--admin-info-light)',
          'info-text': 'var(--admin-info-text)',
          neutral: 'var(--admin-neutral)',
          'neutral-light': 'var(--admin-neutral-light)',
          'neutral-text': 'var(--admin-neutral-text)',
          text: 'var(--admin-text)',
          'text-secondary': 'var(--admin-text-secondary)',
          'text-muted': 'var(--admin-text-muted)',
          border: 'var(--admin-border)',
          'border-hover': 'var(--admin-border-hover)',
          bg: 'var(--admin-bg)',
          surface: 'var(--admin-surface)',
        },
      },
      boxShadow: {
        'admin-sm': 'var(--admin-shadow-sm)',
        'admin': 'var(--admin-shadow)',
        'admin-md': 'var(--admin-shadow-md)',
      },
      borderRadius: {
        'admin': 'var(--admin-radius)',
        'admin-lg': 'var(--admin-radius-lg)',
      },
    },
  },
  plugins: [],
};
